### internal uarch#
set uarch_paths_arr(global_address,fe,global_address_part1_par_fe,SMT) "-through \[get_pins -n par_fe/fe/bpu/bptargettagem/BpPrTakenM122*] -through \[get_pins -n par_fe/fe/bpu/bpstewd/BpPrTakenL0M122*] "
set uarch_paths_arr(global_address,fe,global_address_part2_bpglobalm_par_fe,SMT) "-from \[get_pins -n par_fe/fe/bpu/bpstewd/*Taken*/*] -through \[get_pins -n par_fe/fe/bpu/bpglbe*m/BpStGlPrLkpIndxM121H*] "
set uarch_paths_arr(global_address,fe,global_address_part2_bpminiglobalm_par_fe,SMT) "-from \[get_pins -n par_fe/fe/bpu/bpstewd/*TakenM*/*] -through \[get_pins -n par_fe/fe/bpu/bpminiglbe*m/BpStMiniGlPrLkpIndxM121H*] "
set uarch_paths_arr(bpu_left_loop,fe,bpu_left_loop_par_fe,SMT) "-through \[get_pins -n par_fe/fe/bpu/bptargettagem/Bp*Return*] -through \[get_pins -n par_fe/fe/bpu/bprsbd/Bp*Return*] "
set uarch_paths_arr(sbhit,fe,sb_hit_part1_par_fe,SMT) "-through \[get_pins -n par_fe/fe/ifu/iftlbd/ItPhysTagForSB*] -through \[get_pins -n par_fe/fe/ifu/ifsbd/ItPhysTagForSB*] "
set uarch_paths_arr(sbhit,fe,sb_hit_part2_par_fe,SMT) "-through \[get_pins -n par_fe/fe/ifu/ifsbd/SbHit*] -through \[get_pins -n par_fe/fe/ifu/ifctlc/SbHit*] "
set uarch_paths_arr(ichit,fe,ic_hit_part1_par_fe,SMT) "-through \[get_pins -n par_fe/fe/ifu/iftlbd/ItPhysTagForSB*] -through \[get_pins -n par_fe/fe/ifu/ifmemd/ItPhysTag*M122*] "
set uarch_paths_arr(ichit,fe,ic_hit_part2_par_fe,SMT) "-through \[get_pins -n par_fe/fe/ifu/ifmemd/IcHit*] -through \[get_pins -n par_fe/fe/ifu/ifctlc/IcHit*] "
set uarch_paths_arr(selway,fe,selway_par_fe,SMT) "-through \[get_pins -n par_fe/fe/ifu/ifctlc/IfIcWa*] -through \[get_pins -n par_fe/fe/ifu/ifdatalatchunkd/IfIcWay*] "
set uarch_paths_arr(bpu_loop,fe,bpu_loop_par_fe,SMT) "-through \[get_pins -n par_fe/fe/bpu/bptargettag*m/Bp*Return*] -through \[get_pins -n par_fe/fe/bpu/bpnipd/Bp*Clip*] "
set uarch_paths_arr(bp_target,fe,bpu_target_par_fe,SMT) "-through \[get_pins -n par_fe/fe/bpu/bptargettagem/*SelWay*] -through \[get_pins -n par_fe/fe/bpu/bpnipd/*Bp*Trg*] "
set uarch_paths_arr(dsbhit,fe,dsb_hit_par_fe,SMT) "-through \[get_pins -n par_fe/fe/ifu/ifctlc/*DsbHit*] "
set uarch_paths_arr(bpglbhit,fe,bpglbhit_par_fe,SMT) "-through \[get_pins -n par_fe/fe/bpu/*/*BpGlHitM123H*] "
set uarch_paths_arr(bpnlptarget,fe,bpnlptarget_par_fe,SMT) "-through \[get_pins -n par_fe/fe/bpu/*/*Bpnlptargetm*] "
set uarch_paths_arr(part1,fe,nlp_uarch1,SMT) "-from \[get_cells -hier -n *NlpLocalTagHitM121L* ] -to \[get_cells -hier -n *BpNlpHitTagTM122H* ]"
set uarch_paths_arr(part2,fe,nlp_uarch1,SMT) "-to \[get_cells -hier -n *NlpLocalTagHitM121L* ] -through \[get_nets -hierarchical *NLPLocalTagHitM121H* -n]"
set uarch_paths_arr(part3,fe,nlp_uarch1,SMT) "-thr \[get_cells -hier -n *BpNlpHitTagTM122H* ] -through \[get_nets -hierarchical *NLPLocalTagHitM121H* -n] "
set uarch_paths_arr(part1,fe,nlp_uarch2,SMT) "-through \[get_nets -hierarchical *NlpLPrReadM121H*tag* -n] -through \[get_nets -hierarchical *BpNlpTargetM121H* -n] "
set uarch_paths_arr(part2,fe,nlp_uarch2,SMT) "-from \[get_cells -hier -n *BpNlpTargetM122H* ] -through \[get_nets -hierarchical *BpLpFinalTargetTM122H* -n]"
set uarch_paths_arr(part1,fe,nlp_uarch3,SMT) "-from \[get_cells -hier -n *BpNlpTargetM122H* ] -through \[get_nets -hierarchical *NLPLocalTagHitM121H* -n]"
set uarch_paths_arr(part1,fe,nlp_uarch4,SMT) "-from \[get_cells -hier -n *BpNlpTargetM122H* ] -through \[get_nets -hierarchical *BpLpFinalTargetTM122H* -n] -through \[get_nets -hierarchical *NextLttPre*M121H* -n] -through \[get_cells -hier -n *bptargettagrfip* ] "
set uarch_paths_arr(part2,fe,nlp_uarch4,SMT) "-from \[get_cells -hier -n *BpNlpTargetM122H* ] -through \[get_nets -hierarchical *NextLttPre*M121H* -n] -through \[get_cells -hier -n *bptargettagrfip* ] "

## external uarch##
set uarch_paths_arr(ITLB_Request,fe,ITLB_Request_1,SMT) "-through \[get_pins -n par_fe/itrequestadrm*]"
set uarch_paths_arr(ITLB_Request,fe,ITLB_Request_2,SMT) "-through \[get_pins -n par_fe/itrequestm*]"
set uarch_paths_arr(ITLB_Request,fe,ITLB_Request_3,SMT) "-through \[get_pins -n par_fe/itthreadidm*]"
set uarch_paths_arr(PMH_Response,fe,PMH_Response_1,SMT) "-through \[get_pins -n par_fe/pmitphyadrm*]"
set uarch_paths_arr(PMH_Response,fe,PMH_Response_2,SMT) "-through \[get_pins -n par_fe/pmitrequopm*]"
set uarch_paths_arr(PMH_Response,fe,PMH_Response_3,SMT) "-through \[get_pins -n par_fe/pmitthreadidm*]"
set uarch_paths_arr(PMH_Response,fe,PMH_Response_4,SMT) "-through \[get_pins -n par_fe/pmitgbitm*]"
set uarch_paths_arr(PMH_Response,fe,PMH_Response_5,SMT) "-through \[get_pins -n par_fe/pmitholem*]"
set uarch_paths_arr(PMH_Response,fe,PMH_Response_6,SMT) "-through \[get_pins -n par_fe/pmitpagefltm*]"
set uarch_paths_arr(PMH_Response,fe,PMH_Response_7,SMT) "-through \[get_pins -n par_fe/pmitpsbitm*]"
set uarch_paths_arr(PMH_Response,fe,PMH_Response_8,SMT) "-through \[get_pins -n par_fe/pmitptevm*]"
set uarch_paths_arr(PMH_Response,fe,PMH_Response_9,SMT) "-through \[get_pins -n par_fe/pmitstlbhadamissm*]"
set uarch_paths_arr(PMH_Response,fe,PMH_Response_10,SMT) "-through \[get_pins -n par_fe/pmitubitm*]"
set uarch_paths_arr(IFU_Request,fe,IFU_Request_1,SMT) "-through \[get_pins -n par_fe/ifu2mlcreqm104h_ifadr*]"
set uarch_paths_arr(IFU_Request,fe,IFU_Request_2,SMT) "-through \[get_pins -n par_fe/ifu2mlcreqm104h_ifidtag*]"
set uarch_paths_arr(IFU_Request,fe,IFU_Request_3,SMT) "-through \[get_pins -n par_fe/ifu2mlcreqm104h_ifthreadid]"
set uarch_paths_arr(IFU_Request,fe,IFU_Request_4,SMT) "-through \[get_pins -n par_fe/ifu2mlcreqm104h_ifmemtyp]"
#set uarch_paths_arr(par_fe,IFU_Request_5,SMT) "-through \[get_pins -n par_fe/IFValidReqM124H]"
#set uarch_paths_arr(par_fe,IFU_Request_6,SMT) "-through \[get_pins -n par_fe/ifrequestrep1m*]"
set uarch_paths_arr(MLC_Ack,fe,MLC_Ack,SMT) "-through \[get_pins -n par_fe/mlicmplnackm*]"
set uarch_paths_arr(MLC_Response,fe,MLC_Response_1,SMT) "-through \[get_pins -n par_fe/mlicmplm*]"
set uarch_paths_arr(MLC_Response,fe,MLC_Response_2,SMT) "-through \[get_pins -n par_fe/mlicmplidm*]"
set uarch_paths_arr(MLC_Response,fe,MLC_Response_3,SMT) "-through \[get_pins -n par_fe/mlicmplnackm*]"
set uarch_paths_arr(MLC_Response,fe,MLC_Response_4,SMT) "-through \[get_pins -n par_fe/mlidataidm*]"
set uarch_paths_arr(MLC_Response,fe,MLC_Response_5,SMT) "-through \[get_pins -n par_fe/mlidatapoisonm*]"
set uarch_paths_arr(MLC_Response,fe,MLC_Response_6,SMT) "-through \[get_pins -n par_fe/mlidatatrigllcreqm*]"
set uarch_paths_arr(MLC_Response,fe,MLC_Response_7,SMT) "-through \[get_pins -n par_fe/mliearlywarnm*]"
set uarch_paths_arr(MLC_Response,fe,MLC_Response_8,SMT) "-through \[get_pins -n par_fe/mlihalfvm*]"
set uarch_paths_arr(MLC_Response,fe,MLC_Response_9,SMT) "-through \[get_pins -n par_fe/mlithreadm*]"
set uarch_paths_arr(MLC_Response,fe,MLC_Response_10,SMT) "-through \[get_pins -n par_fe/mlirddatam*]"
#set uarch_paths_arr(par_fe,MLC_Snoop_1,SMT) "-through \[get_pins -n par_fe/mlisnpadrm*]"
set uarch_paths_arr(MLC_Snoop,fe,MLC_Snoop_2,SMT) "-through \[get_pins -n par_fe/mlisnpinvm*]"
#set uarch_paths_arr(par_fe,SMC_Snoop_1,SMT) "-through \[get_pins -n par_fe/DTMEAdrStSMCM403H]"
set uarch_paths_arr(SMC_Snoop,fe,SMC_Snoop_2,SMT) "-through \[get_pins -n par_fe/dtstphysadrvm*]"
#set uarch_paths_arr(par_fe,SMC_Snoop_3,SMT) "-through \[get_pins -n par_fe/mo2ifmeuopvstm*]"
set uarch_paths_arr(SMC_Snoop,fe,SMC_Snoop_4,SMT) "-through \[get_pins -n par_fe/moifsnpadrstm*]"
#set uarch_paths_arr(par_fe,SMC_Snoop_5,SMT) "-through \[get_pins -n par_fe/MO2IfSMCHitM402H]"
set uarch_paths_arr(SMC_Snoop_Results,fe,SMC_Snoop_Results_1,SMT) "-through \[get_pins -n par_fe/ifintsnoophitm*]"
set uarch_paths_arr(SMC_Snoop_Results,fe,SMC_Snoop_Results_2,SMT) "-through \[get_pins -n par_fe/ifsnoophitm*]"
set uarch_paths_arr(BLK_STA,fe,BLK_STA,SMT) "-through \[get_pins -n par_fe/ifhitextsnoopm*]"
#set uarch_paths_arr(par_fe,IDQ-->RAT_uop_1,SMT) "-through \[get_pins -n par_fe/IDUopVM200H]"
#set uarch_paths_arr(par_fe,IDQ-->RAT_uop_2,SMT) "-through \[get_pins -n par_fe/Id*M200H*]"
#set uarch_paths_arr(par_fe,IDQ-->RAT_Imm,SMT) "-through \[get_pins -n par_fe/idimmCM201H*]"
#set uarch_paths_arr(par_fe,RAT-->IDQ_stall,SMT) "-through \[get_pins -n par_fe/RAExtStallt_M202H*]"
#set uarch_paths_arr(par_fe,MOB(MRN,SMT)-->IQ/DSB,SMT) "-through \[get_pins -n par_fe/MRNTrainInfoMnnnH]"
set uarch_paths_arr(RO,fe,RO*_1,SMT) "-through \[get_pins -n par_fe/ROnuke*]"
set uarch_paths_arr(RO,fe,RO*_2,SMT) "-through \[get_pins -n par_fe/Ronew*]"
set uarch_paths_arr(JE,fe,JE_CLEAR,SMT) "-through \[get_pins -n par_fe/jeclearlatem806h]"
set uarch_paths_arr(JE,fe,JE_TAKEN,SMT) "-through \[get_pins -n par_fe/jetakenbrm806h]"
set uarch_paths_arr(IQD_EMPTY,fe,IQD_EMPTY,SMT) "-through \[get_pins -n par_fe/idq_really_emptym148h]"
set uarch_paths_arr(ILD_RESET,fe,ILD_RESET,SMT) "-through \[get_pins -n par_fe/ildpipectlforfem100h_resetstage104]"
set uarch_paths_arr(DSB_QCOUNT,fe,DSB_QCOUNT,SMT) "-through \[get_pins -n par_fe/dsbqcountt_m125h*]"
set uarch_paths_arr(IDL_STALL,fe,IDL_STALL,SMT) "-through \[get_pins -n par_fe/idlsdstallm110h]"
set uarch_paths_arr(IDL_STALL,fe,RD_DATA_LONG,SMT) "-through \[get_pins -n par_fe/readdatahaslongimmm109l]"
set uarch_paths_arr(DSBQT,fe,DSBQT,SMT) "-through \[get_pins -n par_fe/dsbqt_ismsm106h]"
set uarch_paths_arr(DSFDSET,fe,DSFDSET,SMT) "-through \[get_pins -n par_fe/dsfbsetm109h]"
set uarch_paths_arr(PMITHO,fe,PMITHO,SMT) "-through \[get_pins -n par_fe/pmitholem402h]"
set uarch_paths_arr(MITE_IS_CALL,fe,MITE_IS_CALL,SMT) "-through \[get_pins -n par_fe/miteiscallwocallnextm110h]"
set uarch_paths_arr(MOISF,fe,MOISF,SMT) "-through \[get_pins -n par_fe/moifsnpadrstm403h*]"
set uarch_paths_arr(ILD_ENABLE,fe,ILD_ENABLE,SMT) "-through \[get_pins -n par_fe/ildpipectlforfem100h_enablestage101to102]"
set uarch_paths_arr(BPBIT_JENEW,fe,BPBIT_JENEW,SMT) "-through \[get_pins -n par_fe/bpbitjenewmacrobrpremuxm806h]"
set uarch_paths_arr(IFSNOOP_PHYADR,fe,IFSNOOP_PHYADR,SMT) "-through \[get_pins -n par_fe/ifsnoopphyadrm123h*]"
set uarch_paths_arr(IT_REQ,fe,IT_REQ,SMT) "-through \[get_pins -n par_fe/itrequestm104h]"
set uarch_paths_arr(DSB_SYNC,fe,DSB_SYNC,SMT) "-through \[get_pins -n par_fe/dsbqsyncenm124l]"
set uarch_paths_arr(dsbhit,fe,DSBHIT,SMT) "-through \[get_pins -n par_fe/dsbhitwaysnumencm124l*]"
