set uarch_paths_arr(Fma_Src,tmul,FMA_src_ext,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmvsrcdatam306h\[*]]"
set uarch_paths_arr(Fma_Src,tmul,Fma_src_tmbmain_data,SMT) "-from \[get_clocks mclk_*] -through par_tmul/tmu/tmrpt_tmvexvrd_tmvSrcDataM806H* -through \[get_pins par_tmul/tmu/tmb_tmbmains/TmbGlbWrDataMnnnH\[*]\[*]_data\[*]] "
set uarch_paths_arr(Fma_Src,tmul,Fma_src_tmbmain_parity,SMT) "-from \[get_clocks mclk_*] -through par_tmul/tmu/tmrpt_tmvexvrd_tmvSrcDataM806H* -through \[get_pins par_tmul/tmu/tmb_tmbmains/TmbGlbWrDataMnnnH\[*]\[*]_parity] "
set uarch_paths_arr(Tm2Vex,tmul,Tmul_fma_stddata,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tm2vexdatam802h_v_*]"
set uarch_paths_arr(Tm2Vex,tmul,Tmul_fma_stddata_802,SMT) "-from \[get_clocks mclk_*] -through par_tmul/tmu/tmrpt_tmvexvrd_tmStdDataM802H_*"
set uarch_paths_arr(FMA_Srctmul,tmul,Fma_vexvrd_srcdata_309,SMT) "-from \[get_clocks mclk_*] -through par_tmul/tmu/tmrpt_tmvexvrd_tmvSrcDataM309H_reg_* -through par_tmul/tmu/tmrpt_tmvexvrd_tmvSrcDataM806H_reg_*"
set uarch_paths_arr(FMA_Srctmul,tmul,Fma_vexvrd_srcdata_806,SMT) "-from \[get_clocks mclk_*] -through par_tmul/tmu/tmrpt_tmvexvrd_tmvSrcDataM806H_reg_* -through par_tmul/tmu/tmrpt_tmvexvrd_tmvSrcDataM806H*"
set uarch_paths_arr(Meu_Ld,tmul,Ld_Data,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmldwbdatam806h*data*] "
set uarch_paths_arr(Meu_Ld,tmul,Ld_parity,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmldwbdatam806h*parity] "
set uarch_paths_arr(Mains,tmul,Tmbmain_fifo_data,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbmains/TmbGlbWrDataMnnnH\[*]\[*]_data\[*]] -through par_tmul/tmu/tmb_tmbmains/tmbfiforfip_multi_array* -through par_tmul/tmu/tmb_tmbmains/tmbIntWrDataMnn1H_reg_*_data_* "
set uarch_paths_arr(Mains,tmul,Tmbmain_fifo_parity,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbmains/TmbGlbWrDataMnnnH\[*]\[*]_parity] -through par_tmul/tmu/tmb_tmbmains/tmbfiforfip_multi_array* -through par_tmul/tmu/tmb_tmbmains/tmbIntWrDataMnn1H_reg_*_parity "
set uarch_paths_arr(Mains,tmul,Tmbmain_to_reg_data,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbmains/TmbGlbWrDataMnnnH\[*]\[*]_data\[*]] -through par_tmul/tmu/tmb_tmbmains/tmbIntWrDataMnn1H_reg_*_data_*"
set uarch_paths_arr(Mains,tmul,Tmbmain_to_reg_parity,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbmains/TmbGlbWrDataMnnnH\[*]\[*]_parity] -through par_tmul/tmu/tmb_tmbmains/tmbIntWrDataMnn1H_reg_*_parity " 
set uarch_paths_arr(Adata,tmul,cola_data_alu,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmgrid/tmmgridvx*d_tmgaluvs*d/tmAcol*DataM*H\[*]_Data\[*]]"
set uarch_paths_arr(Adata,tmul,cola_frac_alu,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmgrid/tmmgridvx*d_tmgaluvs*d/tmAcol*DataM*H\[*]_FracExtra\[*]]"
set uarch_paths_arr(Adata,tmul,cola_meta_alu,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmgrid/tmmgridvx*d_tmgaluvs*d/tmAcol*MDataM*H\[*]_Fp*]"
set uarch_paths_arr(Adata,tmul,cola_valid_alu,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmgrid/tmmgridvx*d_tmgaluvs*d/tmAcol*ValidM*H]"
set uarch_paths_arr(Bdata,tmul,bdata_alu,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmgrid/tmmgridvx*d_tmgaluvs*d/tmbBData*M*H\[*]_Data\[*]]"
set uarch_paths_arr(Bdata,tmul,bfrac_alu,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmgrid/tmmgridvx*d_tmgaluvs*d/tmbBData*M*H\[*]_FracExtra\[*]]"
set uarch_paths_arr(Bdata,tmul,bmeta_alu,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmgrid/tmmgridvx*d_tmgaluvs*d/tmbBMData*M*H\[*]_Fp*]"
set uarch_paths_arr(CWB,tmul,cwb_alu,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmgrid/tmmgridvx*d_tmgaluvs*d/tmmCWBDataM725H\[*]]"
set uarch_paths_arr(CWB,tmul,cwb_valid_alu,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmgrid/tmmgridvx*d_tmgaluvs*d/tmmCWBValidM724H]"
set uarch_paths_arr(Adata,tmul,bank_diag_adata,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbbanks_dpslice_*_dpindex_*/tmbintrddatamnn2h_0__data\[*]] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/TmbADataM701H\[*]_data\[*]]"
set uarch_paths_arr(Bdata,tmul,bank_diag_bdata,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbbanks_dpslice_*_dpindex_*/tmbintrddatamnn2h_1__data\[*]] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/TmbBDataM702H\[*]_data\[*]]"
set uarch_paths_arr(IntRd,tmul,bank_mnn1h_data,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbbanks_dpslice_*_dpindex_*/tmbintwrdatamnn1h_*__data\[*]]"
set uarch_paths_arr(IntRd,tmul,bank_mnn1h_parity,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbbanks_dpslice_*_dpindex_*/tmbintwrdatamnn1h_*__parity] "
set uarch_paths_arr(IntRd,tmul,bank_mnn2h_0data,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbbanks_dpslice_*_dpindex_*/tmbintrddatamnn2h_0__data\[*]]"
set uarch_paths_arr(IntRd,tmul,bank_mnn2h_0parity,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbbanks_dpslice_*_dpindex_*/tmbintrddatamnn2h_0__parity]"
set uarch_paths_arr(IntRd,tmul,bank_mnn2h_1data,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbbanks_dpslice_*_dpindex_*/tmbintrddatamnn2h_1__data\[*]]"
set uarch_paths_arr(IntRd,tmul,bank_mnn2h_1parity,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbbanks_dpslice_*_dpindex_*/tmbintrddatamnn2h_1__parity]"
set uarch_paths_arr(IntRd,tmul,bank_mnn2h_2data,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbbanks_dpslice_*_dpindex_*/tmbintrddatamnn2h_2__data\[*]]"
set uarch_paths_arr(IntRd,tmul,bank_mnn2h_2parity,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbbanks_dpslice_*_dpindex_*/tmbintrddatamnn2h_2__parity]"
set uarch_paths_arr(IntRd,tmul,bank_mnn2h_3data,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbbanks_dpslice_*_dpindex_*/tmbintrddatamnn2h_3__data\[*]]"
set uarch_paths_arr(IntRd,tmul,bank_mnn2h_3parity,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbbanks_dpslice_*_dpindex_*/tmbintrddatamnn2h_3__parity]"
set uarch_paths_arr(IntRd,tmul,bank_mnn2h_4data,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbbanks_dpslice_*_dpindex_*/tmbintrddatamnn2h_4__data\[*]]"
set uarch_paths_arr(IntRd,tmul,bank_mnn2h_4parity,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbbanks_dpslice_*_dpindex_*/tmbintrddatamnn2h_4__parity]"
set uarch_paths_arr(Adata,tmul,diag_acol_frac,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/tmAcol*DataM*H\[*]_FracExtra\[*]]"
set uarch_paths_arr(Adata,tmul,diag_acol_valid,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/tmAcol*ValidM*H]"
set uarch_paths_arr(Adata,tmul,diag_acoldata,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/tmAcol*DataM*H\[*]_Data\[*]]"
set uarch_paths_arr(Adata,tmul,diag_acolmeta,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/tmAcol*MDataM*H\[*]_Fp*]"
set uarch_paths_arr(Adata,tmul,diag_acolout_data,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/tmAColDataOutM703H_*_\[*]_Data\[*]]"
set uarch_paths_arr(Adata,tmul,diag_acolout_frac,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/tmAColDataOutM703H_*_\[*]_FracExtra\[*]]"
set uarch_paths_arr(Adata,tmul,diag_acolout_meta,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/tmAColMDataOutM702H_*_\[*]_Fp*]"
set uarch_paths_arr(Adata,tmul,diag_adata,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/TmbADataM701H\[*]_data\[*]]"
set uarch_paths_arr(Adata,tmul,diag_aparity,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/TmbADataM701H\[*]_parity]"
set uarch_paths_arr(Bdata,tmul,diag_bdata,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/tmbBDataM704H\[*]\[*]_Data\[*]]"
set uarch_paths_arr(Bdata,tmul,diag_bfrac,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/tmbBDataM704H\[*]\[*]_FracExtra\[*]]"
set uarch_paths_arr(Bdata,tmul,diag_bmeta,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/tmBMDataM703H\[*]\[*]_Fp*]"
set uarch_paths_arr(Bdata,tmul,diag_bparity,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/TmbBDataM702H\[*]_parity]"
set uarch_paths_arr(CWB,tmul,diag_cwb,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/tmmCWBDataM803H\[*]\[*]]"
set uarch_paths_arr(Adata,tmul,diag_raw_data,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/tmARawDataOutM703H_*_\[*]_Data\[*]]"
set uarch_paths_arr(Adata,tmul,diag_raw_frac,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/tmARawDataOutM703H_*_\[*]_FracExtra\[*]]"
set uarch_paths_arr(Adata,tmul,diag_raw_meta,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmm_tmdiagv*d/tmARawMDataOutM702H_*_\[*]_Fp*]"
set uarch_paths_arr(CWB,tmul,mains_cwb,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbmains/tmmCWBDataMnp2H\[*]\[*]]"
set uarch_paths_arr(IntWr,tmul,mains_mnn1h_data,SMT) "-from \[get_clocks mclk_*] -through par_tmul/tmu/tmb_tmbmains/tmbIntWrDataMnn1H_reg_*_*_data_* -through \[get_pins par_tmul/tmu/tmb_tmbmains/tmbIntWrDataMnn1H\[*]\[*]_data\[*]]"
set uarch_paths_arr(IntWr,tmul,mains_mnn1h_parity,SMT) "-from \[get_clocks mclk_*] -through par_tmul/tmu/tmb_tmbmains/tmbIntWrDataMnn1H_reg_*_parity -through \[get_pins par_tmul/tmu/tmb_tmbmains/tmbIntWrDataMnn1H\[*]\[*]_parity]"
set uarch_paths_arr(TmbDout,tmul,mains_mnn2h_data,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbmains/TmbDoutMnn2H\[*]\[*]_data\[*]]"
set uarch_paths_arr(TmbDout,tmul,mains_mnn2h_parity,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbmains/TmbDoutMnn2H\[*]\[*]_parity]"
set uarch_paths_arr(TmbDout,tmul,mains_mnn4h_data,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbmains/TmbDoutMnn4H\[*]\[*]_data\[*]]"
set uarch_paths_arr(TmbDout,tmul,mains_mnn4h_parity,SMT) "-from \[get_clocks mclk_*] -through \[get_pins par_tmul/tmu/tmb_tmbmains/TmbDoutMnn4H\[*]\[*]_parity]"
