#!/bin/bash
# ============================================================================
# TIP + TIMING FIX ANALYSIS — DsbqWrDataBundleValidsM124H
# View with: bash DsbqWrDataBundleValidsM124H_analysis_color.sh
#   or:      bash DsbqWrDataBundleValidsM124H_analysis_color.sh | less -R
# ============================================================================

# Color definitions
RED='\033[1;31m'
GRN='\033[1;32m'
YEL='\033[1;33m'
BLU='\033[1;34m'
MAG='\033[1;35m'
CYN='\033[1;36m'
WHT='\033[1;37m'
DIM='\033[2m'
UND='\033[4m'
BG_RED='\033[41m'
BG_GRN='\033[42m'
BG_BLU='\033[44m'
NC='\033[0m'

echo -e "${BLU}================================================================================${NC}"
echo -e "${WHT}  TIP + TIMING FIX ANALYSIS — ${CYN}DsbqWrDataBundleValidsM124H${NC}"
echo -e "${WHT}  Cross-Partition Timing Path (${MAG}par_fe${NC} → ${MAG}par_msid${NC})${NC}"
echo -e "${BLU}================================================================================${NC}"
echo -e "${DIM}  Design    : core_client (GFC Client A0)${NC}"
echo -e "${DIM}  Daily WA  : FCT26WW10A_dcm_daily-CLK039.bu_postcts${NC}"
echo -e "${DIM}  Config    : n2p_htall_conf4${NC}"
echo -e "${DIM}  Corner    : func.max_high.T_85.typical${NC}"
echo -e "${DIM}  Date      : Mar 2, 2026${NC}"
echo -e "${DIM}  Author    : sunger${NC}"
echo -e "${BLU}================================================================================${NC}"
echo ""

echo -e "${WHT}${UND}EXECUTIVE SUMMARY${NC}"
echo -e "  Signal: ${CYN}DsbqWrDataBundleValidsM124H[0][0:4] + [1][0:4]${NC} — 10-bit bus"
echo -e "  Path:   ${MAG}par_fe${NC} (driver) → ${MAG}par_msid${NC} (receiver)"
echo -e "  Slack:  ${RED}-38 to -83 ps${NC} (ALL 10 bits failing)"
echo -e "  Status: ${RED}No TIP, No RTLFP plan${NC}"
echo ""
echo -e "  TIP alone saves ${GRN}~26ps${NC} (fixes par_msid side only)."
echo -e "  Full closure requires ${YEL}TIP + clock balance + par_fe fixes${NC}."
echo ""

echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${WHT}PATH ANALYSIS — WORST BIT [0][0] (slack = ${RED}-82.7ps${WHT})${NC}"
echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo ""

echo -e "${WHT}${UND}CLOCK SUMMARY${NC}"
echo -e "  Launch ${CYN}mclk_fe${NC}:    105.1 ps"
echo -e "  Capture ${CYN}mclk_msid${NC}:  63.7 ps"
echo -e "  Skew: 63.7 - 105.1 = ${RED}-41.4 ps (UNFAVORABLE)${NC}"
echo -e "  Uncertainty:        -12.0 ps"
echo -e "  Setup time:           1.2 ps"
echo -e "  Period:             186.0 ps"
echo -e "  Data required:      238.9 ps"
echo -e "  Data arrival:       324.6 ps"
echo -e "  Slack:              ${RED}-82.7 ps (VIOLATED, stat adj 3.0)${NC}"
echo ""

echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${MAG}PAR_FE SIDE: 160.6 ps${NC}  (105.1 → 265.7)"
echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${WHT}Cell                        Wire   Cell   Total  Location${NC}"
echo -e "  ${DIM}─────────────────────────── ─────  ─────  ─────  ────────────────${NC}"
echo -e "  FF CK→Q (SDFK D2)            —    14.5   14.5   (1547,486)"
echo -e "  BUFFD12                      0.1    6.7    6.8   (1548,485)"
echo -e "  AOI21 D12                    4.7    4.6    9.3   (1545,432) ${YEL}← 54um wire!${NC}"
echo -e "  INVREPM12                    1.7    4.9    6.6   (1543,432)"
echo -e "  ${RED}XOR2D2${NC}                      ${RED}11.7${NC}    7.5   ${RED}19.2${NC}   (1492,374) ${RED}← 109um wire!${NC}"
echo -e "  INR2D4                       0.0    4.5    4.5   (1492,375)"
echo -e "  NDMUX21D3                    0.1    3.1    3.2   (1492,375)"
echo -e "  NR2D6                        0.0    2.8    2.8   (1492,375)"
echo -e "  AN2SR2D16                    2.0    6.6    8.6   (1489,376)"
echo -e "  ${YEL}BUFFSR2BFYDHD16 ⚠SR2${NC}        3.0    5.9    8.9   (1462,372)"
echo -e "  INVREPM6                    ${RED}14.3${NC}    5.1   ${RED}19.4${NC}   (1461,300) ${RED}← 72um wire!${NC}"
echo -e "  BUFFREPM6                    1.4    6.6    8.0   (1455,301)"
echo -e "  ${YEL}MAOI22D2${NC}                     4.7   10.3   15.0   (1456,307)"
echo -e "  ND2SKRD3                     1.4    7.0    8.4   (1454,307)"
echo -e "  ${YEL}AOAI211D2${NC}                    0.1    4.1    4.2   (1454,307)"
echo -e "  ${YEL}ND3D3${NC}                        0.8    8.8    9.6   (1453,308)"
echo -e "  OA21D8                       3.6    8.3   11.9   (1449,315)"
echo -e "  → boundary pin                                   (1441,297)"
echo -e "  ${DIM}─────────────────────────── ─────  ─────  ─────${NC}"
echo -e "  ${WHT}TOTAL par_fe:               49.6  111.3  ${RED}160.6${NC}"
echo -e "  16 gates, 294um Manhattan"
echo -e "  Spec: 130ps → ${RED}OVER by 30.6ps${NC}"
echo ""

echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${MAG}PAR_MSID SIDE: 58.9 ps${NC}  (265.7 → 324.6)  ${GRN}← TIP TARGET${NC}"
echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${WHT}Cell                        Wire   Cell   Total  Location     Dist${NC}"
echo -e "  ${DIM}─────────────────────────── ─────  ─────  ─────  ──────────── ────${NC}"
echo -e "  par_msid pin                                      (1441,297)"
echo -e "  ${YEL}BUFFSR2SKRD6 ⚠SR2${NC}          ${RED}15.0${NC}    8.3   ${RED}23.3${NC}   (1381,290)   60um"
echo -e "  ${YEL}BUFFSR2BFYD10 ⚠SR2${NC}          1.4    5.0    6.4   (1375,289)    6um"
echo -e "  ${YEL}BUFFSR2SKRD14 ⚠SR2${NC}         ${RED}12.4${NC}    9.9   ${RED}22.3${NC}   (1319,283)   56um"
echo -e "  → FF endpoint                6.9    —      6.9   (1263,284)   56um"
echo -e "  ${DIM}─────────────────────────── ─────  ─────  ─────${NC}"
echo -e "  ${WHT}TOTAL par_msid:             35.7   23.2   ${RED}58.9${NC}"
echo -e "  3 SR2 buffers, 178um Manhattan"
echo -e "  Spec: 36ps → ${RED}OVER by 22.9ps${NC}"
echo ""

echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GRN}TIP GAIN ESTIMATION ON PAR_MSID${NC}"
echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${RED}CURRENT${NC} (auto-routed, lower metals, SR2 buffers):"
echo -e "    Wire: 15.0 + 1.4 + 12.4 + 6.9 = ${RED}35.7ps${NC}"
echo -e "    Cell:  8.3 + 5.0 +  9.9       = ${RED}23.2ps${NC}"
echo -e "    TOTAL:                          ${RED}58.9ps${NC}"
echo ""
echo -e "  ${GRN}WITH TIP${NC} (M17/M18 routing, BUF D18, pin constraint, shielding):"
echo -e "    Wire: ~7  + ~5  + ~5   + ~4   = ${GRN}~21ps${NC}  (upper metal 2x lower R)"
echo -e "    Cell: ~6  +      + ~6         = ${GRN}~12ps${NC}  (2 BUF D18, better spacing)"
echo -e "    TOTAL:                         ${GRN}~33ps${NC}"
echo ""
echo -e "  TIP GAIN: 58.9 - 33 = ${GRN}~26ps${NC}"
echo -e "  par_msid after TIP: ${GRN}~33ps (within 36ps spec ✅)${NC}"
echo ""

echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${WHT}PER-BIT SLACK WITH TIP (+26ps)${NC}"
echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${WHT}Bit      Current    With TIP    Gap remaining${NC}"
echo -e "  ${DIM}──────── ────────── ─────────── ─────────────${NC}"
echo -e "  [0][0]  ${RED}  -83ps${NC}    ${RED}  -57ps${NC}       57ps"
echo -e "  [0][1]  ${RED}  -57ps${NC}    ${RED}  -31ps${NC}       31ps"
echo -e "  [0][2]  ${RED}  -59ps${NC}    ${RED}  -33ps${NC}       33ps"
echo -e "  [0][3]  ${RED}  -65ps${NC}    ${RED}  -39ps${NC}       39ps"
echo -e "  [0][4]  ${RED}  -69ps${NC}    ${RED}  -43ps${NC}       43ps"
echo -e "  [1][0]  ${RED}  -69ps${NC}    ${RED}  -43ps${NC}       43ps"
echo -e "  [1][1]  ${RED}  -38ps${NC}    ${RED}  -12ps${NC}       12ps"
echo -e "  [1][2]  ${RED}  -59ps${NC}    ${RED}  -33ps${NC}       33ps"
echo -e "  [1][3]  ${RED}  -65ps${NC}    ${RED}  -39ps${NC}       39ps"
echo -e "  [1][4]  ${RED}  -57ps${NC}    ${RED}  -31ps${NC}       31ps"
echo ""
echo -e "  TIP fixes par_msid but ${RED}ALL bits still fail${NC} (par_fe is the bottleneck)."
echo ""

echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${YEL}⚠ CLOCK SKEW FINDING${NC}"
echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  Endpoint FF clock latency:   ${RED}63.8ps${NC}"
echo -e "  mclk_msid average latency:  91.0ps"
echo -e "  Delta from average:         ${RED}-27.2ps${NC} (clock ${RED}PENALIZING${NC} this path)"
echo ""
echo -e "  If clock team balances to average → ${GRN}~20ps gain${NC} (realistic)"
echo ""

echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${WHT}ADDITIONAL FIX TECHNIQUES NEEDED${NC}"
echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${WHT}#  Fix                 Gain     Owner         Status${NC}"
echo -e "  ${DIM}── ──────────────────── ──────── ───────────── ─────────────────────${NC}"
echo -e "  ${GRN}1. TIP on par_msid     ~26ps    TIP team      Ready to create .tp${NC}"
echo -e "  ${YEL}2. Clock balance       ~20ps    Clock team    Escalate FF latency${NC}"
echo -e "  ${YEL}3. par_fe cell sizing  ~10ps    par_fe PnR    Request upsizing${NC}"
echo -e "  ${YEL}4. FF duplication      ~15ps    RTL team      Source FF 28+ fanouts${NC}"
echo -e "  ${DIM}5. Spec rebalance       ~5ps    FCT owner     Minor shift${NC}"
echo ""
echo -e "  ${WHT}COMBINED PROJECTION (worst bit [0][0]):${NC}"
echo -e "    ${RED}-83${NC} ${GRN}+26${NC}(TIP) ${GRN}+20${NC}(clk) ${GRN}+10${NC}(size) ${GRN}+15${NC}(FFdup) ${GRN}+5${NC}(spec) = ${YEL}-7ps${NC}"
echo ""
echo -e "  ${WHT}COMBINED PROJECTION (best bit [1][1]):${NC}"
echo -e "    ${RED}-38${NC} ${GRN}+26${NC}(TIP) ${GRN}+20${NC}(clk) = ${GRN}+8ps ✅ (closes with just 2 techniques)${NC}"
echo ""

echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${WHT}KEY OBSERVATIONS${NC}"
echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  1. par_msid has 3 ${YEL}SR2 buffers${NC} (slow slew-rate) — TIP replaces"
echo -e "     them with ${GRN}BUF D18 on M17/M18${NC} upper metals → ${GRN}~26ps gain${NC}"
echo ""
echo -e "  2. par_fe has ${RED}16 gates, 160.6ps${NC} (30ps over 130ps spec), including"
echo -e "     two long wires (${RED}109um, 72um${NC}) and one SR2BFY buffer"
echo ""
echo -e "  3. Clock skew is a ${RED}major hidden contributor${NC} (-27ps vs average)"
echo ""
echo -e "  4. Source FF drives ${RED}28+ boundary ports${NC} — already duplicated once"
echo ""
echo -e "  5. Stage BEFORE source FF: ${RED}-11ps${NC} (no retiming backward)"
echo -e "     Stage AFTER endpoint FF: ${GRN}has margin${NC} (retiming possible)"
echo ""

echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${WHT}${UND}HSD FIX: MOVE MUX TO NEXT CYCLE (DsbqByp124FinalBundleValidsM183H)${NC}"
echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${WHT}WHAT IT MEANS:${NC}"
echo -e "  Currently in par_msid (dsbe/dsbpriomux), a MUX combines:"
echo -e "    - ${CYN}DsbqWrDataBundleValidsM124H${NC} (our signal — write data)"
echo -e "    - ${CYN}DsbqByp124${NC} bypass logic (recycle/exit mask)"
echo -e "  into DsbqByp124FinalBundleValidsM183H."
echo -e "  HSD proposes: ${GRN}move this mux ONE CYCLE LATER${NC}."
echo ""
echo -e "  ${WHT}HOW IT CONNECTS:${NC}"
echo -e "  Same source FF (BpPrTakenOfsetL01M124H) feeds ${RED}BOTH${NC}:"
echo -e "    → DsbqWrDataBundleValids  (our signal, 24 paths, ${RED}-83ps${NC})"
echo -e "    → DsbqByp124RecycExitMask (bypass, 116 paths, ${RED}-42 to -61ps${NC})"
echo -e "  Through the ${RED}SAME boundary ports${NC} (dsbexitpointmaskm124h)!"
echo ""
echo -e "  ${WHT}HOW IT HELPS:${NC}"
echo -e "  1. ${GRN}Reduces par_fe logic depth${NC} (~15-20ps)"
echo -e "     16 gates → ~11 gates (bypass gates removed from this cycle)"
echo -e "  2. ${GRN}Reduces source FF fanout${NC} (~5-10ps)"
echo -e "     28+ ports → ~15 ports (bypass ports no longer needed)"
echo -e "  3. ${GRN}Fixes 116 additional failing paths${NC} to DsbqByp124"
echo -e "     One RTL change → ~140 paths fixed total!"
echo ""
echo -e "  ${WHT}Estimated gain: ${GRN}~25ps${NC}"
echo ""

echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${WHT}${UND}3 FIXES COMBINED: MUX MOVE + TIP + CLOCK SKEW FIX${NC}"
echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  Mux move (HSD):  ${GRN}+25ps${NC}  (par_fe logic 16→11 gates + less fanout)"
echo -e "  TIP:             ${GRN}+26ps${NC}  (par_msid SR2→BUF D18 on M17/M18)"
echo -e "  Clock balance:   ${GRN}+20ps${NC}  (endpoint FF 63.8ps → closer to avg 91ps)"
echo -e "                   ─────"
echo -e "  TOTAL:           ${GRN}+71ps${NC}"
echo ""
echo -e "  ${WHT}Bit      Now     +Mux    +TIP    +Clk    Result${NC}"
echo -e "  ${DIM}──────── ─────── ─────── ─────── ─────── ───────${NC}"
echo -e "  [0][0]  ${RED} -83${NC}     -58     -32     ${RED}-12     -12ps${NC} ⚠️"
echo -e "  [0][1]  ${RED} -57${NC}     -32      -6     ${GRN}+14     +14ps${NC} ✅"
echo -e "  [0][2]  ${RED} -59${NC}     -34      -8     ${GRN}+12     +12ps${NC} ✅"
echo -e "  [0][3]  ${RED} -65${NC}     -40     -14     ${GRN} +6      +6ps${NC} ✅"
echo -e "  [0][4]  ${RED} -69${NC}     -44     -18     ${GRN} +2      +2ps${NC} ✅"
echo -e "  [1][0]  ${RED} -69${NC}     -44     -18     ${GRN} +2      +2ps${NC} ✅"
echo -e "  [1][1]  ${RED} -38${NC}     -13     +13     ${GRN}+33     +33ps${NC} ✅"
echo -e "  [1][2]  ${RED} -59${NC}     -34      -8     ${GRN}+12     +12ps${NC} ✅"
echo -e "  [1][3]  ${RED} -65${NC}     -40     -14     ${GRN} +6      +6ps${NC} ✅"
echo -e "  [1][4]  ${RED} -57${NC}     -32      -6     ${GRN}+14     +14ps${NC} ✅"
echo ""
echo -e "  ${WHT}RESULT: ${GRN}9 of 10 bits PASS ✅${NC}"
echo -e "  Only [0][0] still ${RED}-12ps${NC} → cell sizing (+10ps) closes it"
echo ""

echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${WHT}ACTION ITEMS${NC}"
echo -e "${BLU}═══════════════════════════════════════════════════════════════${NC}"
echo -e "  ${RED}[ ]${NC} 1. Create .tp file for TIP on par_msid side"
echo -e "  ${RED}[ ]${NC} 2. Escalate clock skew to clock team (FF latency 63.8 vs avg 91)"
echo -e "  ${RED}[ ]${NC} 3. Push HSD mux-move fix (DsbqByp124FinalBundleValidsM183H)"
echo -e "  ${RED}[ ]${NC} 4. File request to par_fe PnR for cell upsizing (worst bit [0][0])"
echo -e "${BLU}================================================================================${NC}"
