#!/bin/bash
# ============================================================================
# TIP TOPOLOGY REQUEST — ILGBPQIdM107H[0:5] (6-bit bus)
# View with: bash ILGBPQIdM107H_TIP_solution_proposal_color.sh
#   or:      bash ILGBPQIdM107H_TIP_solution_proposal_color.sh | less -R
# ============================================================================

# Color definitions
RED='\033[1;31m'
GRN='\033[1;32m'
YEL='\033[1;33m'
BLU='\033[1;34m'
MAG='\033[1;35m'
CYN='\033[1;36m'
WHT='\033[1;37m'
DIM='\033[2m'
UND='\033[4m'
BG_RED='\033[41m'
BG_GRN='\033[42m'
BG_BLU='\033[44m'
BG_YEL='\033[43m'
NC='\033[0m'

echo ""
echo -e "${BG_BLU}${WHT}════════════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${BG_BLU}${WHT}  TIP TOPOLOGY REQUEST — ILGBPQIdM107H[0:5] (6-bit bus)                      ${NC}"
echo -e "${BG_BLU}${WHT}  Cross-Partition: par_msid → par_fe                                          ${NC}"
echo -e "${BG_BLU}${WHT}  Date: 01-Mar-2026 | MCLK period: 186 ps                                    ${NC}"
echo -e "${BG_BLU}${WHT}════════════════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${BG_YEL}${WHT}  .tp FILE: /nfs/site/disks/sunger_wa/fc_data/my_learns/TIP/icore.ilgbpqidm107h.tp  ${NC}"
echo ""
echo -e "${CYN}┌──────────────────────────────────────────────────────────────────────────────┐${NC}"
echo -e "${CYN}│${NC} ${WHT}.tp FILE CONTENT (icore.ilgbpqidm107h.tp)${NC}                                     ${CYN}│${NC}"
echo -e "${CYN}├──────────────────────────────────────────────────────────────────────────────┤${NC}"
echo -e "${DIM}#|-------------------------------------------------------------------${NC}"
echo -e "${DIM}#| FILENAME          : icore.ilgbpqidm107h.tp${NC}"
echo -e "${DIM}#| USER              : sunger${NC}"
echo -e "${DIM}#| BLOCK             : icore.design${NC}"
echo -e "${DIM}#| COMMENT           : TIP topology plan for ILGBPQIdM107H[0:5] bus${NC}"
echo -e "${DIM}#|                   : Based on RTLFP plan from icore_plans.tcl${NC}"
echo -e "${DIM}#|-------------------------------------------------------------------${NC}"
echo ""
echo -e "${BLU}  KEY TOPOLOGY PLAN ELEMENTS:${NC}"
echo ""
echo -e "  ${GRN}Nets:${NC}       ILGBPQIdM107H_0_ through ILGBPQIdM107H_5_ (6-bit bus)"
echo -e "  ${GRN}Pins:${NC}       par_msid/ilgbpqidm107h[0:5], par_fe/ilgbpqidm107h[0:5]"
echo -e "  ${GRN}NER:${NC}        M17/M18 layers, BUFFSR2BFYD18 buffer, 170um spacing"
echo -e "  ${GRN}Bundle:${NC}     ilgbpqidm107h_boundle (6 supernets)"
echo -e "  ${GRN}Plan:${NC}       ilgbpqidm107h_tp (group: tip_repeater)"
echo ""
echo -e "  ${YEL}4 NODES:${NC}"
echo -e "    ${YEL}NODE0:${NC}  par_fe   BOUND     bbox_percentage {50.000 50.605}"
echo -e "    ${YEL}NODE1:${NC}  par_msid BOUND     bbox_percentage {50.000 50.000}"
echo -e "    ${YEL}NODE2:${NC}  par_fe   PINS      bbox (no percentage)"
echo -e "    ${YEL}NODE3:${NC}  par_msid PINS      bbox (no percentage)"
echo ""
echo -e "  ${YEL}3 EDGES:${NC}"
echo -e "    ${YEL}EDGE0:${NC}  NODE2 → NODE0 (par_fe pins → par_fe bound),      M18"
echo -e "    ${YEL}EDGE1:${NC}  NODE3 → NODE2 (par_msid pins → par_fe pins),     M18"
echo -e "    ${YEL}EDGE3:${NC}  NODE1 → NODE3 (par_msid bound → par_msid pins),  M17+M18"
echo ""
echo -e "  ${MAG}4 REPEATERS (all BUF D18):${NC}"
echo -e "    ${RED}EDGE0: CORNER_NODE0${NC}  BUF  offset=  5.646 um  (par_fe side)"
echo -e "    ${GRN}EDGE0: REPEATER0${NC}     BUF  offset=110.802 um"
echo -e "    ${GRN}EDGE3: REPEATER1${NC}     BUF  offset= 34.936 um"
echo -e "    ${RED}EDGE3: CORNER_NODE1${NC}  BUF  offset=145.936 um  (par_msid side)"
echo ""
echo -e "  ${CYN}Sizing:${NC}     1.5x height, 1.5x width multiplier"
echo -e "  ${CYN}Shielding:${NC}  half_shield_1w on M17/M18, spread=3um (6-bit bus)"
echo -e "${CYN}└──────────────────────────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "${CYN}┌──────────────────────────────────────────────────────────────────────────────┐${NC}"
echo -e "${CYN}│${NC} ${WHT}NODE LOCATION VERIFICATION${NC} (from port_location_outside_bbox.csv)           ${CYN}│${NC}"
echo -e "${CYN}├──────────────────────────────────────────────────────────────────────────────┤${NC}"
echo -e "  ${BLU}Pin coordinates per bit (nm):${NC}"
echo -e "    Bit | par_msid pin (X, Y)       | par_fe pin (X, Y)"
echo -e "    ----+---------------------------+---------------------------"
echo -e "    [0] | (${YEL}1440672${NC}, ${YEL}245784${NC})         | (${YEL}1441248${NC}, ${YEL}245784${NC})"
echo -e "    [1] | (${YEL}1440672${NC}, ${YEL}246164${NC})         | (${YEL}1441248${NC}, ${YEL}246164${NC})"
echo -e "    [2] | (${YEL}1440672${NC}, ${YEL}246316${NC})         | (${YEL}1441248${NC}, ${YEL}246316${NC})"
echo -e "    [3] | (${YEL}1440672${NC}, ${YEL}240616${NC})         | (${YEL}1441248${NC}, ${YEL}240616${NC})"
echo -e "    [4] | (${YEL}1440672${NC}, ${YEL}245708${NC})         | (${YEL}1441248${NC}, ${YEL}245708${NC})"
echo -e "    [5] | (${YEL}1440672${NC}, ${YEL}245556${NC})         | (${YEL}1441248${NC}, ${YEL}245556${NC})"
echo ""
echo -e "  par_msid pins: X = ${GRN}1440.672${NC} um, Y = 240.6–246.3 um (span ${GRN}5.7 um${NC})"
echo -e "  par_fe   pins: X = ${GRN}1441.248${NC} um, Y = 240.6–246.3 um (span ${GRN}5.7 um${NC})"
echo -e "  X gap between partitions: ${GRN}0.576 um${NC}"
echo ""
echo -e "  ${WHT}Node-to-coordinate mapping:${NC}"
echo -e "    ${YEL}NODE0${NC} (par_fe BOUND):   route start   X = ${GRN}1632.024${NC} um, Y = ${GRN}308.256${NC} um"
echo -e "    ${YEL}NODE2${NC} (par_fe PINS):    par_fe pins   X = ${GRN}1441.248${NC} um, Y = ${GRN}245.024${NC} um"
echo -e "                            ─── ${MAG}EDGE1 crosses boundary (0.576 um)${NC} ───"
echo -e "    ${YEL}NODE3${NC} (par_msid PINS):  par_msid pins X = ${GRN}1440.672${NC} um, Y = ${GRN}245.024${NC} um"
echo -e "    ${YEL}NODE1${NC} (par_msid BOUND): route end     X =  ${GRN}809.856${NC} um, Y = ${GRN}302.328${NC} um"
echo ""
echo -e "  ${WHT}Edge distances (approximate):${NC}"
echo -e "    EDGE0 (NODE2→NODE0): ${CYN}~191 um${NC}  (par_fe pins to par_fe bound)"
echo -e "    EDGE1 (NODE3→NODE2): ${CYN} ~0.6 um${NC} (partition crossing)"
echo -e "    EDGE3 (NODE1→NODE3): ${CYN}~631 um${NC}  (par_msid bound to par_msid pins)"
echo -e "${CYN}└──────────────────────────────────────────────────────────────────────────────┘${NC}"
echo ""
echo ""
echo -e "  ${UND}${WHT}CURRENT PATH (NO TIP) — ILGBPQIdM107H[3] worst bit${NC}  ${BG_RED}${WHT} slack = -34.7 ps ${NC}"
echo -e "  ${DIM}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"
echo ""
echo -e "  ${CYN}par_msid (output)${NC}                                                    ${MAG}par_fe (input)${NC}"
echo -e "       |                                                                    |"
echo -e "   ${CYN}FF(ilgenstrvd)${NC}                                                      ${MAG}FF(ilgctls)${NC}"
echo -e "       |                                                                    |"
echo -e "       ${DIM}9 logic gates${NC}         ${RED}3 auto repeaters (RCO)${NC}        ${RED}3 weak cells${NC}     |"
echo -e "       ${YEL}131.8 ps${NC}              ${RED}31.2 ps${NC}                       ${RED}51.0 ps${NC}          |"
echo -e "       |                     |                             |                |"
echo -e "       |  ${RED}7.2ps${NC} ${RED}3.3ps${NC} ${RED}1.2ps${NC} ${RED}4.1ps${NC} ${RED}7.8ps${NC} ${RED}7.6ps${NC} ${RED}16.7ps${NC} ${RED}9.7ps${NC} ${RED}8.7ps${NC} ${RED}8.3ps${NC} ${RED}7.0ps${NC}"
echo -e "       |  wire  cell  wire  cell  wire  cell  wire   cell  wire  cell  cell"
echo -e "       |    |     |     |     |     |     |     |      |     |     |     |"
echo -e "       +----${RED}INV${NC}---+-----${RED}INV${NC}--+-----${RED}BUF${NC}--+-----${RED}INV${NC}----+----${RED}INV${NC}---+--${RED}MUX${NC}--+"
echo -e "             ${RED}D8${NC}           ${RED}D12${NC}         ${RED}D12${NC}          ${RED}D2${NC}         ${RED}D1!${NC}      ${RED}D1!${NC}"
echo -e "             ${DIM}(auto)${NC}       ${DIM}(auto)${NC}       ${DIM}(auto)${NC}        ${RED}(weak)${NC}     ${RED}(weak)${NC}   ${RED}(weak)${NC}"
echo -e "       |                                     |                                         |"
echo -e "       |${RED}<-------- par_msid: 163 ps --------->|<----------- par_fe: 51 ps ------------->|${NC}"
echo -e "       |           ${RED}(spec 108, OVER 55ps)${NC}     |             ${GRN}(spec 59, UNDER 8ps)${NC}        |"
echo -e "       |                                     |                                         |"
echo -e "  ${DIM}(1368792,109844)${NC}                   ${DIM}(1440672,240616)${NC}                          ${DIM}(1552104,265939)${NC}"
echo -e "   ${DIM}source FF${NC}                          ${DIM}boundary${NC}                                 ${DIM}endpoint FF${NC}"
echo ""
echo ""
echo -e "  ${UND}${WHT}PROPOSED TIP TOPOLOGY${NC}  ${BG_GRN}${WHT} estimated slack ~ -2 ps (bit[3]) ${NC}"
echo -e "  ${DIM}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"
echo ""
echo -e "  ${CYN}par_msid BOUND${NC}                                                           ${MAG}par_fe BOUND${NC}"
echo -e "  ${DIM}(809.9, 302.3)${NC}                                                           ${DIM}(1632.0, 308.3)${NC}"
echo -e "       |                                                                        |"
echo -e "       |   ${BLU}EDGE3 (M17+M18, 631 um)${NC}                      ${BLU}EDGE0 (M18, 191 um)${NC}    |"
echo -e "       |                                                                        |"
echo -e "       |  ┌──────┐  ┌──────┐                          ┌──────┐  ┌──────┐       |"
echo -e "       |  │${GRN} BUF  ${NC}│  │${GRN} BUF  ${NC}│     9 logic    ${MAG}EDGE1${NC}     │${GRN} BUF  ${NC}│  │${GRN} BUF  ${NC}│       |"
echo -e "       +─►│${GRN} D18  ${NC}│─►│${GRN} D18  ${NC}│─►   gates    ─► ${MAG}0.6um${NC} ─►│${GRN} D18  ${NC}│─►│${GRN} D18  ${NC}│─►─────+"
echo -e "       |  │${DIM}REP1  ${NC}│  │${DIM}CORNER${NC}│     131.8ps    crossing   │${DIM}CORNER${NC}│  │${DIM}REP0  ${NC}│       |"
echo -e "       |  │${DIM}@34.9 ${NC}│  │${DIM}NODE1 ${NC}│                           │${DIM}NODE0 ${NC}│  │${DIM}@110.8${NC}│       |"
echo -e "       |  │${DIM}      ${NC}│  │${DIM}@145.9${NC}│     ${DIM}FF(ilgen${NC}              │${DIM}@5.6  ${NC}│  │${DIM}      ${NC}│       |"
echo -e "       |  └──────┘  └──────┘     ${DIM}strvd)${NC}                └──────┘  └──────┘       |"
echo -e "       |                         ${DIM}INV→INV→BUF${NC}                                    |"
echo -e "       |                         ${DIM}(auto reps)${NC}                                    |"
echo -e "       |                                                                        |"
echo -e "       |◄── ${BLU}TIP msid${NC} ──►|◄── logic ──►|◄cross►|◄────── ${BLU}TIP fe${NC} ────────────►|"
echo -e "       |    ${GRN}~15-18 ps${NC}    | ${YEL}131.8 ps${NC}  | ${DIM}~0 ps${NC} |       ${GRN}~15-18 ps${NC}          |"
echo -e "       |                                                                        |"
echo -e "       ${YEL}NODE1${NC}                   ${YEL}NODE3${NC}       ${YEL}NODE2${NC}                          ${YEL}NODE0${NC}"
echo ""
echo -e "                                        Then ${MAG}par_fe internal${NC} (NOT TIP, PnR handles):"
echo -e "                                        ┌──────┐  ┌──────┐  ┌──────┐"
echo -e "                                   ────►│${GRN} INV  ${NC}│─►│${GRN} INV  ${NC}│─►│${GRN} MUX  ${NC}│─► ${MAG}FF(ilgctls)${NC}"
echo -e "                                        │${GRN} D8   ${NC}│  │${GRN} D4!  ${NC}│  │${GRN} D4!  ${NC}│   ${DIM}(1552.1, 265.9)${NC}"
echo -e "                                        │${DIM}~5ps  ${NC}│  │${DIM}~4ps  ${NC}│  │${DIM}~4ps  ${NC}│"
echo -e "                                        └──────┘  └──────┘  └──────┘"
echo -e "                                        ${DIM}(upsized from D2, D1!, D1!)${NC}"
echo -e "                                        ${DIM}par_fe internal: ~21 ps, 113 um${NC}"
echo ""
echo -e "       ${MAG}half_shield_1w on M17/M18 — spread=3um for 6-bit bus${NC}"
echo ""
echo ""
echo -e "  ${UND}${WHT}TIMING GAIN SUMMARY PER STAGE${NC}"
echo -e "  ${DIM}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"
echo ""
echo -e "       +--------------------+----------+-----------+----------+"
echo -e "       | ${WHT}Stage${NC}              | ${RED}Current${NC}  | ${GRN}With TIP${NC}  | ${CYN}Savings${NC}  |"
echo -e "       +--------------------+----------+-----------+----------+"
echo -e "       | par_msid logic     | ${YEL}131.8 ps${NC} | ${YEL}131.8 ps${NC}  |   ${DIM}0 ps${NC}   |"
echo -e "       | par_msid TIP chain | ${RED} 31.2 ps${NC} | ${GRN} 15-18 ps${NC} | ${CYN}13-16 ps${NC} |"
echo -e "       | par_fe data path   | ${RED} 51.0 ps${NC} | ${GRN} ~21 ps${NC}   | ${CYN}~30 ps${NC}   |"
echo -e "       |   ${DIM}(TIP port opt)${NC}   | ${RED}(16.7 w)${NC} | ${GRN}( ~6 w)${NC}   |  ${CYN}~11 ps${NC} |"
echo -e "       |   ${DIM}(cell sizing)${NC}    | ${RED}(25 c)${NC}   | ${GRN}(~13 c)${NC}   |  ${CYN}~12 ps${NC} |"
echo -e "       |   ${DIM}(shield gain)${NC}    |    ${DIM}—${NC}      | ${GRN} ~3-5 ps${NC} |  ${CYN}~4 ps${NC}  |"
echo -e "       | spec shift (+8ps)  |    ${DIM}—${NC}      | ${GRN} +8 ps${NC}   |   ${CYN}8 ps${NC}  |"
echo -e "       +--------------------+----------+-----------+----------+"
echo -e "       | ${WHT}TOTAL path delay${NC}   | ${RED}214.0 ps${NC} | ${GRN}~169 ps${NC}   | ${CYN}~45 ps${NC}   |"
echo -e "       | ${WHT}Slack${NC}              | ${BG_RED}${WHT}-34.7 ps${NC} | ${BG_YEL}${WHT} ~-2 ps${NC}   |          |"
echo -e "       +--------------------+----------+-----------+----------+"
echo ""
echo ""
echo -e "${BG_BLU}${WHT}════════════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${BG_BLU}${WHT}  PROJECTED SLACK PER BIT                                                     ${NC}"
echo -e "${BG_BLU}${WHT}════════════════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  With combined gain of ${CYN}~36-41 ps${NC} (TIP + shield + sizing + spec shift):"
echo ""
echo -e "  +------+---------------+----------------+--------+"
echo -e "  | ${WHT}Bit${NC}  | ${RED}Current Slack${NC} | ${GRN}Projected Slack${NC}| ${WHT}Status${NC} |"
echo -e "  +------+---------------+----------------+--------+"
echo -e "  | [3]  | ${RED}  -34.7 ps${NC}    | ${YEL}   ~+2 ps${NC}      | ${YEL}~MET${NC}   |"
echo -e "  | [2]  | ${RED}  -32.0 ps${NC}    | ${GRN}   ~+5 ps${NC}      | ${GRN}PASS${NC}   |"
echo -e "  | [1]  | ${RED}  -31.4 ps${NC}    | ${GRN}   ~+6 ps${NC}      | ${GRN}PASS${NC}   |"
echo -e "  | [5]  | ${RED}  -29.3 ps${NC}    | ${GRN}   ~+8 ps${NC}      | ${GRN}PASS${NC}   |"
echo -e "  | [4]  | ${RED}  -28.5 ps${NC}    | ${GRN}   ~+9 ps${NC}      | ${GRN}PASS${NC}   |"
echo -e "  | [0]  | ${RED}  -24.6 ps${NC}    | ${GRN}  ~+12 ps${NC}      | ${GRN}PASS${NC}   |"
echo -e "  +------+---------------+----------------+--------+"
echo ""
echo ""
echo -e "${BG_BLU}${WHT}════════════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${BG_BLU}${WHT}  FIX BREAKDOWN                                                               ${NC}"
echo -e "${BG_BLU}${WHT}════════════════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  +--------+-------------------------------------+----------+-----------+"
echo -e "  | ${WHT}Fix${NC}    | ${WHT}Description${NC}                         | ${CYN}Est Gain${NC} | ${WHT}Owner${NC}     |"
echo -e "  +--------+-------------------------------------+----------+-----------+"
echo -e "  | ${BLU}Fix A${NC}  | TIP topology planning               | ${CYN}13-16 ps${NC} | ${MAG}TD team${NC}   |"
echo -e "  | ${BLU}Fix A+${NC} | Half-shield track blocking (M17/M18)| ${CYN} ~3-5 ps${NC} | ${MAG}TD team${NC}   |"
echo -e "  | ${BLU}Fix B${NC}  | Cell sizing on par_fe               | ${CYN}  ~12 ps${NC} | ${MAG}par_fe PnR${NC}|"
echo -e "  | ${BLU}Fix C${NC}  | Spec rebalance (Technique 8)        | ${CYN}   ~8 ps${NC} | ${MAG}FCT/spec${NC}  |"
echo -e "  +--------+-------------------------------------+----------+-----------+"
echo -e "  | ${WHT}TOTAL${NC}  |                                     | ${GRN}36-41 ps${NC} |           |"
echo -e "  +--------+-------------------------------------+----------+-----------+"
echo ""
echo ""
echo -e "${BG_BLU}${WHT}════════════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${BG_BLU}${WHT}  ACTION ITEMS                                                                ${NC}"
echo -e "${BG_BLU}${WHT}════════════════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${RED}[ ]${NC} ${MAG}TD team${NC}: Create TIP topology file for ILGBPQIdM107H[0:5] bus"
echo -e "      - Use ${BLU}ifhitextsnoopm105h.tp${NC} as template"
echo -e "      - Include all 6 bits in single bundle + topology plan"
echo -e "      - Assign ${GRN}M17/M18${NC} layers, plan repeaters with ${GRN}1.5x${NC} multiplier"
echo -e "      - Add ${GRN}half_shield_1w${NC} ivars to ${BLU}pre.tip_implementation.tcl${NC}"
echo -e "      - TIP chain: 4x ${GRN}BUF${NC}(D18) across 3 edges, locked physical_status"
echo ""
echo -e "  ${RED}[ ]${NC} ${MAG}par_fe PnR${NC}: Upsize weak cells"
echo -e "      - ${RED}INVD2${NC}     → ${GRN}INVD8${NC}     (save ~5 ps)"
echo -e "      - ${RED}INVSKFOD1${NC} → ${GRN}INVD4${NC}     (save ~4 ps)"
echo -e "      - ${RED}MUX2D1${NC}    → ${GRN}MUX2D4${NC}    (save ~3 ps)"
echo -e "      - Apply across ${WHT}all 6 bits${NC}"
echo ""
echo -e "  ${RED}[ ]${NC} ${MAG}FCT/spec${NC}: Evaluate spec shift of ${CYN}8 ps${NC} from par_fe to par_msid"
echo -e "      - Current: par_msid=${RED}108 ps${NC} | par_fe=${GRN}59 ps${NC}"
echo -e "      - New:     par_msid=${GRN}116 ps${NC} | par_fe=${YEL}51 ps${NC}"
echo ""
echo -e "  ${RED}[ ]${NC} Validation: Rerun STA after TIP + cell sizing to confirm closure"
echo ""
echo ""
echo -e "${BG_BLU}${WHT}════════════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${BG_BLU}${WHT}  REFERENCE FILES                                                             ${NC}"
echo -e "${BG_BLU}${WHT}════════════════════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${WHT}TIP file created:${NC}"
echo -e "    ${BLU}TIP/icore.ilgbpqidm107h.tp${NC}"
echo ""
echo -e "  ${WHT}TIP reference (passing signal, same budget):${NC}"
echo -e "    ${BLU}/nfs/site/disks/idc_gfc_fct_td/GFC_TIP_WA/tip_files/"
echo -e "    GFCA0_26WW09_5_fp_change/icore.ifhitextsnoopm105h.tp${NC}"
echo ""
echo -e "  ${WHT}Pre-TIP track blocking:${NC}"
echo -e "    ${BLU}/nfs/site/disks/idc_gfc_fct_td/GFC_TIP_WA/tip_files/"
echo -e "    GFCA0_26WW09_5_fp_change/pre.tip_implementation.tcl${NC}"
echo ""
echo -e "  ${WHT}WA path:${NC}"
echo -e "    ${DIM}/nfs/site/disks/idc_gfc_fct_bu_daily/work_area/"
echo -e "    GFC_CLIENT_26ww06b_ww07_6_TIP_clockroute_RCOs-FCT26WW09G_dcm_daily-CLK039.bu_postcts/"
echo -e "    runs/core_client/n2p_htall_conf4/sta_pt/func.max_high.T_85.typical${NC}"
echo ""
