set uarch_paths_arr(JE,msid,JE1,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/je2mswrearlym805h_a* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(JE,msid,JE2,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/jeclearlatem806h -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(JE,msid,JE3,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/idforcejeclrm201h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(JE,msid,JE4,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/jeo2idatam805h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(JE,msid,JE5,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/jeclearlatem805l -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(JE,msid,JE6,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/jetakenbrm806h -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(200H,msid,200H1,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/idmrnactivem200h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(200H,msid,200H2,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/iduopisinterstackm200h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(200H,msid,200H3,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/iduopvm200h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(200H,msid,200H4,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/idismfipdm200h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(200H,msid,200H5,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/idldstm200h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(200H,msid,200H6,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/idlsrcm200h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(200H,msid,200H7,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/idlsrc3typem200h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(200H,msid,200H8,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/idisregregmovm200h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(200H,msid,200H9,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/iduopcodm200h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(200H,msid,200H10,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/idfstackctlm200h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(200H,msid,200H11,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/idmrnablem200h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(m202h,msid,M202H,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/raenhstallt_m202l* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(ifu_mlird,msid,ifu_mlird,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/mlirddatam510h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MSID-FE,msid,MSID-FE1,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/idq_really_emptym148h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MSID-FE,msid,MSID-FE2,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/ildpipectlforfem100h_resetstage104* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MSID-FE,msid,MSID-FE3,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/dsbqcountt_m125h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MSID-FE,msid,MSID-FE4,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/idlsdstallm110h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MSID-FE,msid,MSID-FE5,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/readdatahaslongimmm109h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MSID-FE,msid,MSID-FE6,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/dsbqt_ismsm106h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MSID-FE,msid,MSID-FE7,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/dsfbsetm109h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MSID-FE,msid,MSID-FE8,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/pmitholem402h -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MSID-FE,msid,MSID-FE9,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/miteiscallwocallnextm110h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MSID-FE,msid,MSID-FE10,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/moifsnpadrstm403h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MSID-FE,msid,MSID-FE11,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/ildpipectlforfem100h_enablestage101to102 -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MSID-FE,msid,MSID-FE12,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/ifsnoopphyadrm123h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MSID-FE,msid,MSID-FE13,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/bpbitjenewmacrobrpremuxm806h -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(FE-MSID,msid,FE-MSID1,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/dsbhitwaysnumencm124l* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(FE-MSID,msid,FE-MSID2,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/itrequestm104h -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(FE-MSID,msid,FE-MSID3,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/dsbqsyncenm124l* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MEU-MSID,msid,MEU-MSID,SMT) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/dtstphysadrvm404h* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(MSROM,msid,MSROM) "-through \[get_pins par_msid/msid/ms/msrom_arrays/MSuromNUIPM* -nocase]"
set uarch_paths_arr(ifadr,msid,ifadr) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/ifu2mlcreqrep1m104h_ifadr* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(ifthread,msid,ifthread) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/ifu2mlcreqrep1m104h_ifthread* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(mlisnp,msid,mlisnp) "-from \[ get_clocks mclk_*] -through \[get_pins par_msid/mlisnp* -nocase] -to \[ get_clocks mclk_*]"
set uarch_paths_arr(dsbread,msid,dsbread) "-through \[get_pins par_msid/msid/dsbe/dsbe_arrays/dsbbankindex*rfip*/*rfip*/* -nocase] -through \[get_pins par_msid/msid/dsbe/dsbe_arrays/*dsbdata*/*dsbdata*/* -nocase]"


