##############################################################################
# dcl1dataeccissecm408h — par_pmh Fixes
# Generated by master_timing_fix_cookbook.txt | Mode 4+7 | WW12A CLK045
#
# Source-side fixes are SIO2PO-class (D1, G1) — file HSD to implement.
# No direct ICC2 ECO on MBIT banks.
##############################################################################

# ============================================================================
# D1 — Bound source FF (bit[1], MB2)
# ============================================================================
# Instance: dcu_l1/dcl1data/auto_vector_MBIT_DcL1RdDataIntM408H_reg_1__1__250__MBIT_DcL1RdDataIntM408H_reg_1__1__251_
# Bank: MB2 (bits 250, 251)
# Action: SIO2PO HSD — bound closer to dcl1dataeccissecm408h[1] port
# Gain: 10-30ps | Risk: MED

# ============================================================================
# G1 — MBIT demerge (bit[0], MB4)
# ============================================================================
# Instance: dcu_l1/dcl1data/auto_vector_MBIT_DcL1RdDataIntM408H_reg_0__1__74__MBIT_DcL1RdDataIntM408H_reg_0__1__76__MBIT_DcL1RdDataIntM408H_reg_0__1__77__MBIT_DcL1RdDataIntM408H_reg_0__1__78_
# Bank: MB4 (bits 74, 76, 77, 78)
# Action: Demerge MB4 → MB2 or singles, then bound closer to port
# Gain: enables better placement | Risk: MED

# ============================================================================
# A1 — Spec rebalance (update in spec XML)
# ============================================================================
# Current:  par_pmh = 143.0ps  par_meu = 25.0ps
# Proposed: par_pmh = 153.0ps  par_meu = 15.0ps  (+10ps to pmh)

# ============================================================================
# D4 — Port relocation (file SIO2PO HSD)
# ============================================================================
# Current Y distance: 136μm (bit[1]), 106μm (bit[0])
# Action: Slide port to reduce vertical distance
# Gain: 5-15ps | Risk: MED

# ============================================================================
# SIO2PO HSD Template
# ============================================================================
# Title: "dcl1dataeccissecm408h par_pmh→par_meu: bound source FF + demerge MB4"
# Signal: dcl1dataeccissecm408h[0:1]
# Source: par_pmh   Dest: par_meu
# WNS: -39ps (bit[1]=-25ps, bit[0]=-15ps)
# Request:
#   1. Bound MBIT_DcL1RdDataIntM408H[1] (MB2) closer to port
#   2. Demerge MBIT_DcL1RdDataIntM408H[0] (MB4→MB2) and bound
#   3. Port relocation to reduce 136μm Y distance

# ============================================================================
# Verification (after SIO implements)
# ============================================================================
# pt_client -model func.max_high.T_85.typical -par par_pmh report_timing \
#   -through *dcl1dataeccissecm408h* -max_paths 10

puts "INFO: par_pmh fixes are SIO2PO-class — file HSD with above details"
