##############################################################################
# dcl1dataeccissecm408h — par_meu ECO Fixes
# Generated by master_timing_fix_cookbook.txt | Mode 4+7 | WW12A CLK045
#
# Direct ICC2 ECO: C1 (upsize D2→D4), C4 (buffer — conditional)
##############################################################################

set signal "dcl1dataeccissecm408h"
set partition "par_meu"

# ============================================================================
# FIX C1a — Upsize endpoint FF bit[1]: D2 → D4
# Instance: dcu_l0/dcregs/DcL1ErrorInSliceM409H_reg_1_
# Cell: SDFQTXGOPTBBD2BWP156HPNPN3P48CPDULVT
# Gain: 2-5ps | Risk: LOW
# ============================================================================
puts "\n=== FIX C1a: Upsize DcL1ErrorInSliceM409H_reg_1_ D2→D4 ==="

set inst "dcu_l0/dcregs/DcL1ErrorInSliceM409H_reg_1_"
set current_ref [get_attribute [get_cells $inst] ref_name]
puts "Current: $current_ref"

set target_ref "SDFQTXGOPTBBD4BWP156HPNPN3P48CPDULVT"
if {[string match "*D2*" $current_ref]} {
    size_cell $inst $target_ref
    puts "DONE: Upsized → $target_ref"
} else {
    puts "SKIP: not D2 (current: $current_ref)"
}

# ============================================================================
# FIX C1b — Upsize endpoint FF bit[0]: D2 → D4
# Instance: dcu_l0/dcregs/DcL1DataSECM409H_reg_0_
# Cell: SDFQTXGD2BWP156HPNPN3P48CPDULVTLL
# Gain: 2-5ps | Risk: LOW
# ============================================================================
puts "\n=== FIX C1b: Upsize DcL1DataSECM409H_reg_0_ D2→D4 ==="

set inst "dcu_l0/dcregs/DcL1DataSECM409H_reg_0_"
set current_ref [get_attribute [get_cells $inst] ref_name]
puts "Current: $current_ref"

set target_ref "SDFQTXGD4BWP156HPNPN3P48CPDULVTLL"
if {[string match "*D2*" $current_ref]} {
    size_cell $inst $target_ref
    puts "DONE: Upsized → $target_ref"
} else {
    puts "SKIP: not D2 (current: $current_ref)"
}

# ============================================================================
# FIX C4 — Insert buffer on Y wire (CONDITIONAL — after D4 decision)
# Gain: 5-15ps | Risk: MED
# ============================================================================
puts "\n=== FIX C4: Buffer on Y wire — CONDITIONAL ==="
puts "WARNING: Apply AFTER SIO2PO D4 (port relocation) decision"
# Uncomment after D4:
# set net [get_nets -of_objects [get_pins dcu_l0/dcregs/DcL1ErrorInSliceM409H_reg_1_/D]]
# insert_buffer $net BUFFD8BWP156HPNPN3P48CPDULVT

# ============================================================================
# POST-FIX
# ============================================================================
puts "\n=== POST-FIX ==="
puts "Run: route_eco ; check_routes"
puts "Expected C1a+C1b gain: 4-10ps"
puts "Remaining: bit[1]=-25+5=-20ps  bit[0]=-15+5=-10ps"
puts "Need SIO2PO (D1/D4/D3) + spec rebalance (A1) for full closure"
